version: '3.8'

services:
  api-gateway-service:
    hostname: api-gateway-service
    image: $IMAGE_TAG
    deploy:
      mode: global

    command: ash -c "cd /opt/api-gateway-service && java -jar *.jar --spring.profiles.active=prod --spring.cloud.config.label=master --spring.cloud.config.uri=http://properties-service:8893"
    ports:
      - "9000:9000"
    networks:
      - Production-Network
    volumes:
       - /etc/localtime:/etc/localtime:ro
networks:
  Production-Network:
   name: Production-Network
   driver: overlay
