version: '3.8'
services:
  postgres:
      container_name: postgres
      hostname: postgres
      image: postgres:13.1
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: aIZAWBbmHos8MjoJDkVJ
      ports:
        - 5432:5432
  keycloak:
      container_name: keycloak
      hostname: keycloak
      image: quay.io/keycloak/keycloak:latest
      # command: bash -c "rm -rf /opt/jboss/keycloak/standalone/deployments/ir.kit-keycloak-rocket-db-sync-1.0-SNAPSHOT.jar"
      environment:
         DB_VENDOR: POSTGRES
         DB_ADDR: postgres
         DB_DATABASE: keycloak
         DB_USER: keycloak
         DB_SCHEMA: public
         DB_PASSWORD: aIZAWBbmHos8MjoJDkVJ
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: aIZAWBbmHos8MjoJDkVJ
         PROXY_ADDRESS_FORWARDING: "true"
         DEBUG: "true"
         KEYCLOAK_LOGLEVEL: "DEBUG"
         DEBUG_PORT: "*:8787"
      ports:
        - '8080:8080'
        - '8787:8787'
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /opt/keycloak/data:/opt/jboss/keycloak/standalone/deployments
      depends_on:
        - postgres

volumes:
  postgres_data:
      name: postgres_dat
      driver: local
