version: '3.8'

services:
  postgres:
      container_name: postgres
      hostname: postgres
      image: postgres:13.1
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: aIZAWBbmHos8MjoJDkVJ
      ports:
        - 5432:5432
  keycloak:
      container_name: keycloak
      hostname: keycloak
      image: quay.io/keycloak/keycloak:latest
      environment:
         DB_VENDOR: POSTGRES
         DB_ADDR: postgres
         DB_DATABASE: keycloak
         DB_USER: keycloak
         DB_SCHEMA: public
         DB_PASSWORD: aIZAWBbmHos8MjoJDkVJ
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: aIZAWBbmHos8MjoJDkVJ
         PROXY_ADDRESS_FORWARDING: "true"
         DEBUG_PORT: "*:8787"
      ports:
        - '8081:8080'
        - '8787:8787'
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - keycloak_data:/opt/jboss/keycloak/
        - /etc/hosts:/etc/hosts
      depends_on:
        - postgres

volumes:
  postgres_data:
      name: postgres_dat
      driver: local
  keycloak_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/opt/keycloak/data'
